/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://nfftlfpbbngorc6sxktd3sqz3e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dhsa3iddjvhnjjmpk2t2b6a4hu",
    "aws_cognito_identity_pool_id": "us-east-1:d09e6c02-2807-4076-a7bd-067fb3e2a0c3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_z3XMeF6mh",
    "aws_user_pools_web_client_id": "6aamnjr2uoc64ii2qkadljpfht",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "machicoulisbfb421939b4a49bd89baef4eda185a1c7d6ba-machicouli",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "machicoulis-20250704132620-hostingbucket-machicouli",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://dw3nw1iq6wxe3.cloudfront.net"
};


export default awsmobile;
